name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ github.token }}

      - name: Audit casks
        run: brew audit --cask --tap strubio-ray/quicklook

      - name: Style check
        run: brew style --cask strubio-ray/quicklook/syntax-highlight strubio-ray/quicklook/qlmarkdown

      - name: Livecheck
        run: brew livecheck --tap strubio-ray/quicklook
